//Converts HTML generated by bootstrap studio to PUG template used by the web server
const html2pug = require('html2pug');
const fs = require('fs');
const path = require('path');

var htmlPath = path.join(__dirname, 'bootstrap-studio-export');
var pugPath;
const fileArray = ['404', 'config' ,'documents', 'index', 'logging', 'login', 'profile', 'register','table', 'incomplete', 'testing', 'delete_user'];
const exclusions = ['404'];
const overwrite = true; //If false, PUG files are written to folder not accessed by the web server.

pugPath = overwrite ? path.join(__dirname, 'views') : path.join(__dirname, 'views','converted');

for (var file of fileArray) {
    if (!exclusions.includes(file)) {
        convertToPug(file);
    }
}
function convertToPug(fileName) {
    const sourcePath = path.join(htmlPath, fileName + '.html');
    const destPath = path.join(pugPath, fileName + '.pug');
    var htmlFileContent = '';
    let pugFileContent = '';
     
    htmlFileContent = fs.readFileSync(sourcePath, 'utf8', function (err,data) {
        if (err) {
          return console.log(err);
        }
        //htmlFileContent = data;    //Might need a deep copy
        console.log(data);
    });

    
    pugFileContent = html2pug(htmlFileContent,{tabs: true});
    
    fs.writeFileSync(destPath, pugFileContent, (err) => {
        // throws an error, you could also catch it here
        if (err) throw err;

    });
    console.log('Saved ' + fileName + '.html' );
    
};